apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: qotd-rating-alerts
  namespace: qotd
spec:
  groups:
  - name: rating
    rules:
    - alert: RatingVeryHighRequestLatency
      expr: sum(rate(http_request_duration_seconds_sum{container="qotd-rating",method="GET",route="/ratings/#val",status="2XX"}[1m])) / sum(rate(http_request_duration_seconds_count{container="qotd-rating",method="GET",route="/ratings/#val",status="2XX"}[1m])) > 1.0
      for: 1m
      labels:
        severity: Critical
      annotations:
        summary: Rating service response time over past minute is significantly high (> 1.0s)
        expiryTime: "300"
    - alert: RatingVeryHighCPUUsage
      expr: rate(process_cpu_seconds_total{container="qotd-rating"}[1m]) > 0.020
      for: 1m
      labels:
        severity: Critical
      annotations:
        summary: Rating service CPU usage very high
        expiryTime: "300"
    - alert: RatingVeryHighMemoryUsage
      expr: nodejs_heap_size_used_bytes{container="qotd-rating"} > 60000000
      for: 1m
      labels:
        severity: Critical
      annotations:
        summary: Rating service Mem usage very high
        expiryTime: "300"
    - alert: RatingServiceDown
      expr: (up{container="qotd-rating"} OR on() vector(0)) != 1
      for: 20s
      labels:
        severity: Critical
      annotations:
        summary: Rating service down.
        expiryTime: "300"
    - alert: RatingResponse5xxTooHigh
      expr: sum(rate(http_requests_total{container="qotd-rating",method="GET",route="/ratings/#val",status="5XX"}[1m])) / sum(rate(http_requests_total{container="qotd-rating",method="GET",route="/ratings/#val",status="2XX"}[1m])) > 0.3
      for: 1m
      labels:
        severity: Critical
      annotations:
        summary: Rating service reponds with 5xx status far more than expected.
        expiryTime: "300"
    - alert: RatingResponse4xxTooHigh
      expr: sum(rate(http_requests_total{container="qotd-rating",method="GET",route="/ratings/#val",status="4XX"}[1m])) / sum(rate(http_requests_total{container="qotd-rating",method="GET",route="/ratings/#val",status="2XX"}[1m])) > 0.3
      for: 1m
      labels:
        severity: Critical
      annotations:
        summary: Rating service reponds with 4xx status far more than expected.
        expiryTime: "300"