kind: Deployment
apiVersion: apps/v1
metadata:
  name: qotd-engraving
  namespace: qotd
  labels:
    app: qotd
    tier: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qotd-engraving
  template:
    metadata:
      labels:
        app: qotd-engraving
    spec:
      restartPolicy: Always
      containers:
        - name: qotd-engraving
          image: quay.io/jconallen_us/qotd-engraving-service/ppc64:v4.1.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3006
              protocol: TCP
          env:
            - name: LOG_LEVEL
              value: "INFO"
            - name: ENABLE_INSTANA
              value: "true"
            - name: ANOMALY_GENERATOR_URL
              value: "http://qotd-usecase-qotd-load.apps.bstern6.cp.fyre.ibm.com/services/engraving"
            - name: SUPPLY_CHAIN_URL
              value: ""
            - name: SUPPLY_CHAIN_SIMULATE
              value: "true"
          livenessProbe:
            httpGet:
              path: /health
              port: 3006
            initialDelaySeconds: 60
            timeoutSeconds: 20
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3006
            initialDelaySeconds: 5
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          resources:
            requests:
              cpu: "25m"
              memory: "200Mi"
            limits:
              cpu: "200m"
              memory: "800Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: qotd-engraving
  namespace: qotd
  labels:
    app: qotd
    tier: api
spec:
  type: ClusterIP
  ports:
    - port: 3006
      targetPort: 3006
      protocol: TCP
      name: http
  selector:
    app: qotd-engraving


